### ISSUE TITLE
Package gimp-python no longer sourceable - will your plugin work without it ?

### ISSUE THREAD

**Issue by corinthian13** [manu12121999/RemoveBG-GIMP#10]
I've tried sourcing gimp-python as the usual:

sudo apt install gimp-python 

just gives 

E: Unable to locate package gimp-python

Will your background removal plugin work without it ?

**Comment by manu12121999** [comment]
This happens when requests is not correctly installed. And installing it is quite tricky, since gimp has an own version on python, so make sure it's is installed for the python of gimp and not your normal python. And how to do it depends on how you installed gimp in the first place. Perhaps you can try the alternative installation method in the section for installing it on windows

**Comment by corinthian13** [comment]
I have no Windows machine, I'm proud to say.

Look, does your background remove thing do anything I can't manually do on GIMP ?

**Comment by corinthian13** [comment]
Christ.

All you're doing is uploading to remove.bg ?

I thought you had all fancy image analysis code and stuff like that.

I was clicking a checker button instead of selecting Layer > Transparency > Remove Alpha Channel

Okay, thanks.
