### ISSUE TITLE
NameError: global name 'requests' is not defined

### ISSUE THREAD

**Issue by moraybon** [manu12121999/RemoveBG-GIMP#12]
Get the following error when running the plug in, any help please
System win10

Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 741, in response
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 362, in run_script
    return apply(function, params)
  File "C:\Users\Mo\AppData\Roaming\GIMP\2.10\plug-ins\remove_background.py", line 96, in remove_background
    response = requests.post(
NameError: global name 'requests' is not defined

**Comment by Ocelotsden** [comment]
Same here.
 Removebg shows in filters
It asks for and accepts key
it runs and progress bar goes to end
Then the Global name request error pops up. 

I've removed and reinstalled Python multiple times and even tried older version, but no luck. 


![Screenshot 2022-10-07 155144](https://user-images.githubusercontent.com/42783561/194647752-9787702a-8fe3-4abe-944d-9dce6162a221.png)

**Comment by MikeUSNRet** [comment]
And... Add me to the growing list of people that are getting this same error.   Have uninstalled gimp and plugins, re-installed gimp from both gimp site and the microsoft store.  have run and updated python, still no luck.

**Comment by Ocelotsden** [comment]
I actually finally solved mine today.

 I had uninstalled/reinstalled both Python and Gimp multiple times. Even tried older versions of Python and nothing worked. Anyway, one last time I uninstalled Gimp, but instead of reinstalling from the files downloaded directly from Gimp, I installed gimp from the Windows Store as a Windows app. Then after placing the py file in the plugins folder and running the python files again from an administrative command prompt, it finally worked. After entering my key, it completed and removed the background of a photo.

 I don't know if it was just something weird with my system or if it will work for others, but all I can think of is that Gimp from the Windows Store uses different directories in the install.  Maybe the plugin was able to find all the files that way. Not sure, but it's finally working for me.

**Comment by moraybon** [comment]
Ocelotsden, did that and still did not work for me. thanks tho for posting a update

**Comment by MikeUSNRet** [comment]
A little over a month later and I'm still having this issue.  have resintalled Python, Gimp, the plugin and updated pip etc etc etc and still no go  Any ideas on how to fix this?:

**Comment by manu12121999** [comment]
i just updated the plugin. Now it should work without requests.
